"""
PDF report generation service.
"""
from io import BytesIO
from datetime import datetime
from pathlib import Path
from reportlab.lib import colors

# --- PDF Color/Footer Constants ---
PRIMARY_COLOR = colors.HexColor('#3498DB')
HEADER_COLOR = colors.HexColor('#2C3E50')
SUCCESS_COLOR = colors.green
WARNING_COLOR = colors.HexColor('#E67E22')
FOOTER_TEXT = "Generated by ASET Marking System © 2026"
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import mm
from web.services.analysis import FullAnalysis, LearningAreaResult



from typing import Optional

class ReportService:
    """Generates branded PDF reports for students."""

    def __init__(self, assets_dir: Optional[Path] = None):
        self.assets_dir = Path(assets_dir) if assets_dir else None

    def generate_student_report(self, analysis: FullAnalysis, student_name: str = "Student") -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        elements = []
        styles = getSampleStyleSheet()
        # Custom styles
        title_style = ParagraphStyle(
            'Title', parent=styles['Title'], fontSize=22, textColor=PRIMARY_COLOR, alignment=1, spaceAfter=12
        )
        header_style = ParagraphStyle(
            'Header', parent=styles['Heading2'], fontSize=14, textColor=HEADER_COLOR, alignment=0, spaceAfter=8
        )
        # 1. Header
        elements.append(Paragraph("Student Performance Report", title_style))
        elements.append(Paragraph(f"Name: {student_name}", header_style))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", header_style))
        elements.append(Spacer(1, 8))
        # 2. Score Summary Table
        # Try to extract scores from analysis.summary or fallback
        summary = getattr(analysis, 'summary', {})
        reading_score = summary.get('reading_score', 0)
        reading_max = summary.get('reading_max', 0)
        qrar_score = summary.get('qrar_score', 0)
        qrar_max = summary.get('qrar_max', 0)
        writing_score = summary.get('writing_score', 0)
        total_score = reading_score + qrar_score + writing_score
        total_max = reading_max + qrar_max
        summary_data = [
            ["Subject", "Score", "Max"],
            ["Reading", str(reading_score), str(reading_max)],
            ["QR/AR", str(qrar_score), str(qrar_max)],
            ["Writing", str(writing_score), "-"],
            ["Total", str(total_score), str(total_max)],
        ]
        summary_table = Table(summary_data, hAlign='LEFT', colWidths=[60*mm, 30*mm, 30*mm])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), PRIMARY_COLOR),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('GRID', (0,0), (-1,-1), 0.5, HEADER_COLOR),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 16))
        # 3. Reading Analysis Section
        reading_areas = analysis.subject_areas.get('Reading', [])
        elements.append(Paragraph("Reading Analysis", header_style))
        elements.append(self._area_table(reading_areas))
        elements.append(Spacer(1, 12))
        # 4. QR/AR Analysis Section
        qrar_areas = analysis.subject_areas.get('QR/AR', [])
        elements.append(Paragraph("QR/AR Analysis", header_style))
        elements.append(self._area_table(qrar_areas))
        elements.append(Spacer(1, 16))
        # 5. Footer
        elements.append(Paragraph(FOOTER_TEXT, ParagraphStyle('Footer', fontSize=8, textColor=HEADER_COLOR, alignment=1)))
        doc.build(elements)
        return buffer.getvalue()

    def _area_table(self, area_results: list) -> Table:
        # Table columns: Area | % | Status
        data = [["Learning Area", "%", "Status"]]
        for area in area_results:
            percent = f"{area.percentage:.1f}%"
            status = area.status
            data.append([getattr(area, 'area', 'Unknown'), percent, status])
        table = Table(data, hAlign='LEFT', colWidths=[60*mm, 30*mm, 40*mm])
        style = TableStyle([
            ('BACKGROUND', (0,0), (-1,0), PRIMARY_COLOR),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('GRID', (0,0), (-1,-1), 0.5, HEADER_COLOR),
        ])
        # Conditional formatting for status column
        for i, area in enumerate(area_results, start=1):
            status = area.status
            if status == "Done well":
                style.add('TEXTCOLOR', (2,i), (2,i), SUCCESS_COLOR)
            else:
                style.add('TEXTCOLOR', (2,i), (2,i), WARNING_COLOR)
        table.setStyle(style)
        return table
