"""
PDF report generation service.

Generates professional, branded PDF reports for students with:
- Header/footer images on every page
- Score summary tables
- Vertical bar charts comparing student vs max scores
- Strengths and Areas for Improvement analysis
"""
from io import BytesIO
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Callable

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, 
    Table, TableStyle, Image, KeepTogether, PageBreak
)
from reportlab.graphics.shapes import Drawing, String, Rect
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.legends import Legend

from web.services.analysis import FullAnalysis, LearningAreaResult


# --- PDF Color Constants ---
PRIMARY_COLOR = colors.HexColor('#3498DB')      # Main blue
HEADER_COLOR = colors.HexColor('#2C3E50')       # Dark header
SUCCESS_COLOR = colors.HexColor('#27AE60')      # Green for "Done well"
WARNING_COLOR = colors.HexColor('#E74C3C')      # Red for "Needs improvement"
LIGHT_BLUE = colors.HexColor('#EBF5FB')         # Light blue background
CHART_BLUE = colors.HexColor('#5DADE2')         # Chart bar color
CHART_GREY = colors.HexColor('#BDC3C7')         # Max score bar color

FOOTER_TEXT = "Generated by ASET Marking System © 2026"

# Page dimensions
PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 20 * mm


class ReportService:
    """Generates branded PDF reports for students."""

    def __init__(self, assets_dir: Optional[Path] = None):
        """
        Initialize the report service.
        
        Args:
            assets_dir: Path to directory containing header.png and footer.png
        """
        if assets_dir:
            self.assets_dir = Path(assets_dir)
        else:
            # Default to web/static/images
            self.assets_dir = Path(__file__).parent.parent / "static" / "images"
        
        self._header_path = self.assets_dir / "header.png" if self.assets_dir else None
        self._footer_path = self.assets_dir / "footer.png" if self.assets_dir else None
        self._styles = self._create_styles()

    def _create_styles(self) -> dict:
        """Create custom paragraph styles for the report."""
        base_styles = getSampleStyleSheet()
        
        return {
            'title': ParagraphStyle(
                'ReportTitle',
                parent=base_styles['Title'],
                fontSize=24,
                textColor=HEADER_COLOR,
                alignment=TA_CENTER,
                spaceAfter=6 * mm,
                fontName='Helvetica-Bold'
            ),
            'subtitle': ParagraphStyle(
                'Subtitle',
                parent=base_styles['Normal'],
                fontSize=12,
                textColor=HEADER_COLOR,
                alignment=TA_CENTER,
                spaceAfter=4 * mm,
            ),
            'section_header': ParagraphStyle(
                'SectionHeader',
                parent=base_styles['Heading2'],
                fontSize=14,
                textColor=colors.white,
                alignment=TA_LEFT,
                spaceBefore=8 * mm,
                spaceAfter=4 * mm,
                fontName='Helvetica-Bold',
                leftIndent=8,
                rightIndent=8,
            ),
            'subsection': ParagraphStyle(
                'Subsection',
                parent=base_styles['Heading3'],
                fontSize=12,
                textColor=HEADER_COLOR,
                alignment=TA_LEFT,
                spaceBefore=4 * mm,
                spaceAfter=2 * mm,
                fontName='Helvetica-Bold',
            ),
            'body': ParagraphStyle(
                'Body',
                parent=base_styles['Normal'],
                fontSize=10,
                textColor=colors.black,
                alignment=TA_LEFT,
                spaceAfter=2 * mm,
            ),
            'footer': ParagraphStyle(
                'Footer',
                parent=base_styles['Normal'],
                fontSize=8,
                textColor=HEADER_COLOR,
                alignment=TA_CENTER,
            ),
            'strength': ParagraphStyle(
                'Strength',
                parent=base_styles['Normal'],
                fontSize=10,
                textColor=SUCCESS_COLOR,
                fontName='Helvetica-Bold',
            ),
            'improvement': ParagraphStyle(
                'Improvement',
                parent=base_styles['Normal'],
                fontSize=10,
                textColor=WARNING_COLOR,
                fontName='Helvetica-Bold',
            ),
        }

    def _add_header_footer(self, canvas, doc):
        """Draw header and footer images on each page."""
        canvas.saveState()
        
        # Header image
        if self._header_path and self._header_path.exists():
            try:
                # Draw header at top of page, centered
                header_width = PAGE_WIDTH - (2 * MARGIN)
                header_height = 25 * mm
                canvas.drawImage(
                    str(self._header_path),
                    MARGIN,
                    PAGE_HEIGHT - MARGIN - header_height,
                    width=header_width,
                    height=header_height,
                    preserveAspectRatio=True,
                    mask='auto'
                )
            except Exception:
                pass  # Silently skip if image can't be loaded
        
        # Footer image
        if self._footer_path and self._footer_path.exists():
            try:
                footer_width = PAGE_WIDTH - (2 * MARGIN)
                footer_height = 15 * mm
                canvas.drawImage(
                    str(self._footer_path),
                    MARGIN,
                    MARGIN,
                    width=footer_width,
                    height=footer_height,
                    preserveAspectRatio=True,
                    mask='auto'
                )
            except Exception:
                pass
        
        # Footer text
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(HEADER_COLOR)
        canvas.drawCentredString(
            PAGE_WIDTH / 2,
            MARGIN - 5 * mm,
            f"{FOOTER_TEXT} | Page {doc.page}"
        )
        
        canvas.restoreState()

    def _create_score_chart(self, scores: dict) -> Drawing:
        """
        Create a vertical bar chart comparing student scores to max scores.
        
        Args:
            scores: Dictionary with subject names as keys and (score, max) tuples as values
        
        Returns:
            Drawing object containing the chart
        """
        drawing = Drawing(160 * mm, 80 * mm)
        
        chart = VerticalBarChart()
        chart.x = 15 * mm
        chart.y = 15 * mm
        chart.width = 130 * mm
        chart.height = 55 * mm
        
        # Prepare data: [[student_scores], [max_scores]]
        subjects = list(scores.keys())
        student_scores = [scores[s][0] for s in subjects]
        max_scores = [scores[s][1] for s in subjects]
        
        chart.data = [student_scores, max_scores]
        
        # Category names (subjects)
        chart.categoryAxis.categoryNames = subjects
        chart.categoryAxis.labels.fontName = 'Helvetica'
        chart.categoryAxis.labels.fontSize = 9
        chart.categoryAxis.labels.angle = 0
        
        # Value axis
        chart.valueAxis.valueMin = 0
        chart.valueAxis.valueMax = max(max_scores) + 5 if max_scores else 40
        chart.valueAxis.valueStep = 5
        chart.valueAxis.labels.fontName = 'Helvetica'
        chart.valueAxis.labels.fontSize = 8
        
        # Bar styling
        chart.bars[0].fillColor = CHART_BLUE
        chart.bars[0].strokeColor = None
        chart.bars[1].fillColor = CHART_GREY
        chart.bars[1].strokeColor = None
        chart.barWidth = 10 * mm
        chart.groupSpacing = 15 * mm
        
        drawing.add(chart)
        
        # Add legend
        legend = Legend()
        legend.x = 50 * mm
        legend.y = 2 * mm
        legend.dx = 8
        legend.dy = 8
        legend.fontName = 'Helvetica'
        legend.fontSize = 9
        legend.boxAnchor = 'sw'
        legend.columnMaximum = 1
        legend.strokeWidth = 0.5
        legend.strokeColor = HEADER_COLOR
        legend.deltax = 50
        legend.deltay = 0
        legend.autoXPadding = 5
        legend.colorNamePairs = [
            (CHART_BLUE, 'Student Score'),
            (CHART_GREY, 'Maximum Score'),
        ]
        drawing.add(legend)
        
        return drawing

    def _create_score_table(self, scores: dict, writing_score: int = 0) -> Table:
        """
        Create a score summary table.
        
        Args:
            scores: Dictionary with subject names as keys and (score, max) tuples
            writing_score: Writing score to include
        
        Returns:
            Table object with formatted scores
        """
        data = [["Subject", "Score", "Max Score", "Percentage"]]
        
        total_score = 0
        total_max = 0
        
        for subject, (score, max_score) in scores.items():
            percentage = (score / max_score * 100) if max_score > 0 else 0
            data.append([
                subject,
                str(score),
                str(max_score),
                f"{percentage:.1f}%"
            ])
            total_score += score
            total_max += max_score
        
        # Add writing score row
        data.append(["Writing", str(writing_score), "-", "-"])
        
        # Add total row
        total_percentage = (total_score / total_max * 100) if total_max > 0 else 0
        data.append([
            "Total (excl. Writing)",
            str(total_score),
            str(total_max),
            f"{total_percentage:.1f}%"
        ])
        
        table = Table(data, colWidths=[50 * mm, 25 * mm, 25 * mm, 30 * mm])
        table.setStyle(TableStyle([
            # Header row
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            
            # Data rows
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            
            # Alternating row colors
            ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, LIGHT_BLUE]),
            
            # Total row
            ('BACKGROUND', (0, -1), (-1, -1), HEADER_COLOR),
            ('TEXTCOLOR', (0, -1), (-1, -1), colors.white),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            
            # Grid
            ('GRID', (0, 0), (-1, -1), 0.5, HEADER_COLOR),
            ('BOX', (0, 0), (-1, -1), 1, HEADER_COLOR),
            
            # Padding
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        return table

    def _create_analysis_section(
        self,
        subject_name: str,
        area_results: List[LearningAreaResult]
    ) -> List:
        """
        Create a detailed analysis section for a subject.
        
        Args:
            subject_name: Name of the subject
            area_results: List of LearningAreaResult objects
        
        Returns:
            List of flowable elements
        """
        elements = []
        
        # Section header with background
        header_table = Table(
            [[Paragraph(f"{subject_name} Analysis", self._styles['section_header'])]],
            colWidths=[PAGE_WIDTH - 2 * MARGIN]
        )
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), PRIMARY_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(header_table)
        elements.append(Spacer(1, 4 * mm))
        
        # Separate into strengths and improvements
        strengths = [a for a in area_results if a.status == "Done well"]
        improvements = [a for a in area_results if a.status == "Needs improvement"]
        
        # Create two-column layout
        col_width = (PAGE_WIDTH - 2 * MARGIN - 10 * mm) / 2
        
        # Strengths column content
        strengths_content = []
        strengths_content.append(Paragraph("✓ Strengths (Done Well)", self._styles['subsection']))
        if strengths:
            for area in strengths:
                strengths_content.append(
                    Paragraph(
                        f"• {area.area} ({area.percentage:.0f}%)",
                        self._styles['strength']
                    )
                )
        else:
            strengths_content.append(
                Paragraph("No areas identified as strengths yet.", self._styles['body'])
            )
        
        # Improvements column content
        improvements_content = []
        improvements_content.append(Paragraph("⚠ Areas for Improvement", self._styles['subsection']))
        if improvements:
            for area in improvements:
                improvements_content.append(
                    Paragraph(
                        f"• {area.area} ({area.percentage:.0f}%)",
                        self._styles['improvement']
                    )
                )
        else:
            improvements_content.append(
                Paragraph("Great work! No areas needing improvement.", self._styles['body'])
            )
        
        # Build the two-column table
        strengths_cell = []
        for item in strengths_content:
            strengths_cell.append(item)
        
        improvements_cell = []
        for item in improvements_content:
            improvements_cell.append(item)
        
        # Create inner tables for each column to stack content
        def _stack_content(content_list):
            return Table(
                [[item] for item in content_list],
                colWidths=[col_width - 8 * mm]
            )
        
        two_col_data = [[
            _stack_content(strengths_content),
            _stack_content(improvements_content)
        ]]
        
        two_col_table = Table(two_col_data, colWidths=[col_width, col_width])
        two_col_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            # Left column border
            ('BOX', (0, 0), (0, 0), 1, SUCCESS_COLOR),
            ('BACKGROUND', (0, 0), (0, 0), colors.HexColor('#E8F8F5')),
            # Right column border
            ('BOX', (1, 0), (1, 0), 1, WARNING_COLOR),
            ('BACKGROUND', (1, 0), (1, 0), colors.HexColor('#FDEDEC')),
        ]))
        
        elements.append(two_col_table)
        elements.append(Spacer(1, 6 * mm))
        
        # Detailed breakdown table
        if area_results:
            elements.append(Paragraph("Detailed Breakdown", self._styles['subsection']))
            
            detail_data = [["Learning Area", "Correct", "Total", "%", "Status"]]
            for area in area_results:
                status_color = SUCCESS_COLOR if area.status == "Done well" else WARNING_COLOR
                detail_data.append([
                    area.area,
                    str(area.correct),
                    str(area.total),
                    f"{area.percentage:.1f}%",
                    area.status
                ])
            
            detail_table = Table(
                detail_data,
                colWidths=[55 * mm, 18 * mm, 18 * mm, 18 * mm, 35 * mm]
            )
            
            style = TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('ALIGN', (0, 0), (0, -1), 'LEFT'),
                ('GRID', (0, 0), (-1, -1), 0.5, HEADER_COLOR),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BLUE]),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ])
            
            # Color-code status column
            for i, area in enumerate(area_results, start=1):
                if area.status == "Done well":
                    style.add('TEXTCOLOR', (4, i), (4, i), SUCCESS_COLOR)
                    style.add('FONTNAME', (4, i), (4, i), 'Helvetica-Bold')
                else:
                    style.add('TEXTCOLOR', (4, i), (4, i), WARNING_COLOR)
                    style.add('FONTNAME', (4, i), (4, i), 'Helvetica-Bold')
            
            detail_table.setStyle(style)
            elements.append(detail_table)
        
        return elements

    def generate_student_report(
        self,
        analysis: FullAnalysis,
        student_name: str = "Student",
        writing_score: int = 0
    ) -> bytes:
        """
        Generate a complete PDF report for a student.
        
        Args:
            analysis: FullAnalysis object containing all analysis data
            student_name: Name of the student
            writing_score: Writing score to include in the report
        
        Returns:
            PDF file as bytes
        """
        buffer = BytesIO()
        
        # Create document with custom page template
        doc = BaseDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN + 30 * mm,  # Extra space for header
            bottomMargin=MARGIN + 20 * mm,  # Extra space for footer
        )
        
        # Create frame for content
        frame = Frame(
            doc.leftMargin,
            doc.bottomMargin,
            PAGE_WIDTH - doc.leftMargin - doc.rightMargin,
            PAGE_HEIGHT - doc.topMargin - doc.bottomMargin,
            id='normal'
        )
        
        # Create page template with header/footer callback
        template = PageTemplate(
            id='report',
            frames=frame,
            onPage=self._add_header_footer
        )
        doc.addPageTemplates([template])
        
        elements = []
        
        # === TITLE ===
        elements.append(Paragraph("Student Performance Report", self._styles['title']))
        elements.append(Paragraph(
            f"<b>{student_name}</b> | Generated: {datetime.now().strftime('%d %B %Y')}",
            self._styles['subtitle']
        ))
        elements.append(Spacer(1, 6 * mm))
        
        # === CALCULATE SCORES ===
        # Extract scores from subject_areas
        scores = {}
        
        reading_areas = analysis.subject_areas.get('Reading', [])
        if reading_areas:
            reading_correct = sum(a.correct for a in reading_areas)
            reading_total = sum(a.total for a in reading_areas)
            scores['Reading'] = (reading_correct, reading_total)
        
        qr_areas = analysis.subject_areas.get('Quantitative Reasoning', [])
        if qr_areas:
            qr_correct = sum(a.correct for a in qr_areas)
            qr_total = sum(a.total for a in qr_areas)
            scores['QR'] = (qr_correct, qr_total)
        
        ar_areas = analysis.subject_areas.get('Abstract Reasoning', [])
        if ar_areas:
            ar_correct = sum(a.correct for a in ar_areas)
            ar_total = sum(a.total for a in ar_areas)
            scores['AR'] = (ar_correct, ar_total)
        
        # === SCORE SUMMARY TABLE ===
        if scores:
            elements.append(self._create_score_table(scores, writing_score))
            elements.append(Spacer(1, 8 * mm))
        
        # === SCORE CHART ===
        if scores:
            chart_title = Table(
                [[Paragraph("Score Comparison Chart", self._styles['section_header'])]],
                colWidths=[PAGE_WIDTH - 2 * MARGIN]
            )
            chart_title.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), PRIMARY_COLOR),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ]))
            elements.append(chart_title)
            elements.append(Spacer(1, 4 * mm))
            
            chart = self._create_score_chart(scores)
            elements.append(chart)
            elements.append(Spacer(1, 8 * mm))
        
        # === ANALYSIS SECTIONS ===
        for subject_key in ['Reading', 'Quantitative Reasoning', 'Abstract Reasoning']:
            area_results = analysis.subject_areas.get(subject_key, [])
            if area_results:
                section_elements = self._create_analysis_section(subject_key, area_results)
                # Use KeepTogether to avoid awkward page breaks within sections
                elements.append(KeepTogether(section_elements))
                elements.append(Spacer(1, 4 * mm))
        
        # === BUILD PDF ===
        doc.build(elements)
        
        return buffer.getvalue()
